
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  thymleaf:
    encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/manddang?characterEncoding=UTF-8&serverTimezone=UTC
    username: manddangAdmin
    password: 1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
